# -*- coding: utf-8 -*-
"""storing_database.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o8dLsESA8WlSNeblTB7-g8hg7PbA2RDy
"""

import duckdb
import pandas as pd

# Database name
db_name = "database.db" # Please input db_name you want

con = duckdb.connect(db_name)

# Table name
table_name = "Well_Information"

con.sql(f"Drop table if exists {table_name}")

# Create a table and load data from a CSV file
con.execute(f"CREATE TABLE {table_name} AS SELECT * FROM read_csv_auto('final_preprocessed.csv')")

# Query the top 5 rows from the table
result = con.execute(f"SELECT * FROM {table_name} LIMIT 5")

# Print the result
print(result.fetchall())